src/components/GradientRoundedButton/GradientRoundedButton.stories.tsx, src/components/GradientRoundedButton/GradientRoundedButton.tsx, src/utils/types.tsx
Added GradientRoundedButton
[[TRI-23]](https://linear.app/tricker-sirius/issue/TRI-23/design-systems-gradientroundedbutton)
1. `npm run storybook`
2. Go to components/GradientRoundedButton
example code:
```
<div className='flex gap-4 items-center '>
<GradientRoundedButton size="md" icon={<PlayIcon fillColor='black'/>} onClick={() => {alert("Play")}}/>
<GradientRoundedButton size="sm" icon={<PlayIcon fillColor='black'/>} onClick={() => {alert("Play")}}/>
<GradientRoundedButton size="md" icon={<StopIcon fillColor='black'/>} onClick={() => {alert("Stop")}}/>
<GradientRoundedButton size="sm" icon={<StopIcon fillColor='black'/>} onClick={() => {alert("Stop")}}/>
</div>
```
result:
=> Tri 23/design systems gradient rounded button

src/components/ProfileButton/ProfileButton.stories.tsx, src/components/ProfileButton/ProfileButton.tsx
Profile button design and story implemented.
[[TRI-19]](https://linear.app/tricker-sirius/issue/TRI-19/design-systems-profilebutton)
1. Run `npm run storybook`
2. Try it using different images.
You can trying changing the image url or using any icon in the app.
=> TRI-19: Design system's profile button

src/components/Switch/Switch.stories.tsx, src/components/Switch/Switch.tsx
Added Switch component and its story
[[TRI-24]](https://linear.app/tricker-sirius/issue/TRI-24/design-systems-switch)
1. npm run storybook
2. Go to components/Switch
example code: 
```
const [ checked, setChecked ] = React.useState(false)
const handleChecked = (checked: boolean) => {
setChecked(checked)
}
return (
<>
<Switch onChecked={(checked) => handleChecked(checked)} />
<div className="p-3">
<p className="text-lg">Switch is {checked ? "on" : "off"}</p>
</div>
</>
)
```
=> Add Switch component and its story

src/components/Pill/Pill.stories.tsx
Added more Pill component stories
=> Hotfix - Added new Pill Stories

src/components/NavbarItem/NavbarItem.stories.tsx
Added more stories to Storybook
=> Hotfix - Added new NavbarItem Stories

src/components/Switch/Switch.tsx
Added random id so when there are multiple switches they don't interfere with each other
=> Add random id

src/components/RoundedIconButton/RoundedIconButton.stories.tsx, src/components/RoundedIconButton/RoundedIconButton.tsx, src/utils/icons/BlockedIcon.tsx
Added RoundedIconButton
[[TRI-21]](https://linear.app/tricker-sirius/issue/TRI-21/design-systems-roundediconbutton)
1. `npm run storybook`
2. Go to components/RoundedIconButton
=> Tri 21/design systems rounded icon button

src/components/GridList/GridList.stories.tsx, src/components/GridList/GridList.tsx
Added GridList switch component
[[TRI-20]](https://linear.app/tricker-sirius/issue/TRI-20/design-systems-gridlist-component)
1. npm run storybook
2. Go to components/GridList
The switch receives three props
disabled: boolean
checked: boolean
onChecked: callback function (receives state)
=> Add GridList component and its story

.env, .eslintrc.json, package-lock.json, package.json, src/App.tsx, src/components/Layout/Layout.tsx, src/components/Layout/PrivateRoute.tsx, src/components/Layout/Router.tsx, src/service/AxiosInterceptor.ts, src/service/Cookies.ts, src/service/service.ts, vite.config.ts
Setup react router dom for managing private and public routes.
[[TRI-47]](https://linear.app/tricker-sirius/issue/TRI-47/setup-react-router-for-private-and-public-routes)
1. Clone the backend repo.
2. Run the backend server.
3. Run `npm install` to install new dependencies.
4. Check src/service configuration about AxiosInterceptors and Cookies.
5. Check components/Layout to see Routes configuration.
=> TRI-47: Setup react router for private and public routes

src/components/SearchBar/SearchBar.stories.tsx, src/components/SearchBar/SearchBar.tsx
Create SearchBar and its story to visualize it.
[[TRI-71]](https://linear.app/tricker-sirius/issue/TRI-71/design-systems-search-bar-component)
1. Run `npm run storybook`
2. Check Components/SearchBar
3. Check its stories.
=> TRI-71: Design System's Search Bar Component

src/components/CategoryIcon/CategoryIcon.stories.tsx, src/components/PriorityIcon/PriorityIcon.stories.tsx
Fix some errors in Category Icon and Priority Icon stories.
=> Hotfix: Fix category and priority icons stories

.eslintrc.json, package-lock.json, package.json, src/App.tsx
Set up React Query 
1. `npm i`
2. import { useQuery } from '@tanstack/react-query'
3. const { isPending, error, data } = useQuery({...})
docs: https://tanstack.com/query/latest/docs/framework/react/overview
=> Add @tanstack/react-query and @tanstack/eslint-plugin-query

.storybook/main.ts, package-lock.json, package.json, src/components/Dropdown/Dropdown.tsx, src/components/SidebarNav/Sidebar.stories.tsx, src/components/SidebarNav/SidebarNav.tsx, src/utils/types.tsx, vite.config.ts
Added sidebar navigation menu component, added username property in User interface.
[[TRI-76]](https://linear.app/tricker-sirius/issue/TRI-76/design-systems-sidebar-navigation-menu-component)
1. `npm run storybook`
2.  Go to components/SidebarNav
Note that the selected variant in some buttons won't work in storybook since they work using url parameters, but were tested in a test page.
=> Tri 76/design systems sidebar navigation menu component

src/components/CategoryIcon/CategoryIcon.stories.tsx, src/components/CategoryIcon/CategoryIcon.tsx, src/components/ChildIcon/ChildIcon.tsx, src/components/PriorityIcon/PriorityIcon.stories.tsx, src/components/PriorityIcon/PriorityIcon.tsx
Fixed border color in PriorityIcon & CategoryIcon
=> Refactor category and priority icons

src/components/SidebarNav/SidebarNav.tsx
Added class "min-h-10" to profile button
before
after
=> Hotfix: Update ProfileButton className in SidebarNav component

index.html, src/components/Modal/Modal.tsx
Added Modal component
[[TRI-94]](https://linear.app/tricker-sirius/issue/TRI-94/implement-the-modal-component)
1. `npm yarn dev`
2.  try it on a page, you can use this example:
```
const [ showModal, setShowModal ] = useState(false)
<button onClick={() => {setShowModal(true)}} className="text-white text-sm underline">Need help?</button>
<Modal show={showModal} onClose={() => {setShowModal(false)}}>
<div className="w-[400px] h-[400px] bg-white">
<h1>Modal Content</h1>
<p>Modal content goes here</p>
<button onClick={() => {setShowModal(false)}}>Close Modal</button>
</div>
</Modal>
```
It receives the following props:
onClose: function
show: boolean
=> Tri 94/implement the modal component

src/utils/reactQuery/mutationExample.tsx, src/utils/reactQuery/queryExample.tsx, src/utils/reactQuery/readme.md
Added examples for useQuery & useMutation in /utils
[[TRI-99]](https://linear.app/tricker-sirius/issue/TRI-99/setup-react-query-for-fetching-data-from-the-be)
=> Tri 99/setup react query for fetching data from the be

src/utils/email-templates/access_request.html
Added access request html email template
[[TRI-111]](https://linear.app/tricker-sirius/issue/TRI-111/request-access-email)
1. go to utils/email-templates & open access_request.html
Variables and buttons url must be placed from the BE
=> Add access request html

src/components/ProjectMail/ProjectMail.stories.tsx, src/components/ProjectMail/ProjectMail.tsx, src/redux/hooks.tsx, src/redux/user.tsx
Create project mail screen that integrates redux to retrieve the project name.
[[TRI-104]](https://linear.app/tricker-sirius/issue/TRI-104/project-mail-screen)
1. Run `npm run storybook`
2. Check Components/ProjectMail
3. Check responsiveness using either the local tool or the browser dev tools.
=> TRI-104: Project Mail Screen

src/utils/email-templates/access_granted.html
Added granted access html email template.
[[TRI-114]](https://linear.app/tricker-sirius/issue/TRI-114/granted-access-email)
1. Go to utils/email-templates
2. Open access_granted.html
Here is an example about how is the view as an email.
=> TRII-114: Granted Access Email

src/utils/email-templates/declined_request.html
Added declined request html email template.
[[TRI-116]](https://linear.app/tricker-sirius/issue/TRI-116/declined-request-email)
1. Go to utils/email-templates
2. Open declined_request.html
Here is an example about how is the view as an email.
=> TRI-116: Declined Request Email

src/utils/email-templates/project_integration_finished.html
Added declined request html email template.
[[TRI-115]](https://linear.app/tricker-sirius/issue/TRI-115/project-has-finished-integrating-email)
1. Go to utils/email-templates
2. Open project_integration_finished.html
Here is an example about how is the view as an email.
Mobile:
=> TRI-115: Project has finished integrating email

src/components/Spinner/Spinner.stories.tsx, src/components/Spinner/Spinner.tsx
Added Spinner component
[[TRI-136]](https://linear.app/tricker-sirius/issue/TRI-136/custom-circular-progress-component-creation)
1. `npm run storybook`
2. go to [Storybook](http://localhost:6006/?path=/docs/components-spinner--docs)
The component receives a size prop (in pixels) and a variant prop ('primary' or 'secondary')
=> Tri 136/custom circular progress component creation

src/pages/Login/EmptyProjectPage.tsx
Fixed responsiveness
[[TRI-142]](https://linear.app/tricker-sirius/issue/TRI-142/non-invited-page-ui-fix)
=> Update EmptyProjectPage styling

src/components/Layout/PrivateRoute/PrivateRouteWrapper.tsx, src/components/Layout/Router.tsx, src/components/Spinner/Spinner.tsx
Fixed home rendering when user doesn't have any project
[[TRI-138]](https://linear.app/tricker-sirius/issue/TRI-138/in-the-im-a-project-manager-team-member-view-the-home-is-rendered)
=> Tri 138/in the im a project manager team member view the home is rendered

src/components/Input/Input.tsx, src/data-provider/service.ts, src/pages/InitialIntegration/InitialIntegrationPage.tsx
Fixed DOM nesting error at input component and refactor InitialIntegrationPage to setActualMemberProviderId
=> Hotfix/dom nesting error & integrator fix

.github/workflows/deploy.yml, README.md
A short description
[Insert ticket link here]
1. [First Step]
2. [Second Step]
3. [and so on...]
Please add any images or screenshots that may help to explain the issue or the changes made.
[Add any other context about the pull request here.]
=> Hotfix: GH Action

src/components/Filter/Filter.stories.tsx, src/components/Filter/Filter.tsx
Add the Assignee filter and Out of est to the Filters component
[[TRI-148]](https://linear.app/tricker-sirius/issue/TRI-148/add-the-assignee-filter-and-out-of-est-to-the-filters-component)
1. yarn storybook
2. go to components/Filter
=> Tri 148/add the assignee filter and out of est to the filters component

src/components/Layout/PrivateRoute/PrivateRoute.tsx
Refactor PrivateRoute component, now when the BE is not running, it won't let the user access to any page and will redirect him to the login page
1. Shut down the BE and try to access "/", "/setup" or "/login/role"
=> Refactor PrivateRoute component to handle unauthorized access

.github/workflows/tests.yml
Create a pipeline that runs all vite tests and build the project to detect any inconsistency.
[[TRI-152]](https://linear.app/tricker-sirius/issue/TRI-152/github-action-to-build-the-fe-and-run-all-vite-tests)
1. Create a pull request to dev/main.
2. Check if the GH action is running.
=> TRI-152: Github action to Build the FE and run all vite tests

src/components/Filter/Filter.tsx, src/components/FilterSection/FilterSection.tsx, src/components/Layout/Router.tsx, src/components/TicketCard/TicketCard.tsx, src/components/TicketListWrapper/TicketListWrapper.tsx, src/components/TicketsSection/TicketsSection.tsx
Create 'my-team' page reutilizing TicketsSection component and add different filters whether the user is PM or not.
[[TRI-147]](https://linear.app/tricker-sirius/issue/TRI-147/implementation-of-the-my-team-page)
1. Run `npm run dev`
2. Check `my-team` page design and filters.
3. Change user role to developer ID in db to check that is working well.
=> TRI-147: Implementation of the my team page

src/components/Timer/Timer.tsx, src/data-provider/query.ts, src/data-provider/service.ts
There was an error in time that shown NAN because of the parsing
1. Run `npm run dev`
2. Check the timer.
=> Hotfix: Timer component

src/components/TicketList/MockedTicket.ts, src/components/TicketList/TicketList.tsx, src/components/TicketListSmallDisplay/MockedTickets.ts, src/components/TicketListSmallDisplay/TicketListSmallDisplay.tsx, src/components/TicketsSection/TicketsSection.tsx, src/components/Timer/Timer.tsx, src/redux/user.tsx, src/utils/types.tsx
Add stop tracking modal when you are tracking a ticket and another ticket is clicked
=> Hotfix: add stop tracking modal
